/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as InstructionsRouteImport } from './routes/instructions'
import { Route as IzvanBulgariaRouteImport } from './routes/izvan-bulgaria'
import { Route as NewsRouteImport } from './routes/news'
import { Route as PrivacyNoticeRouteImport } from './routes/privacy-notice'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as VhodRouteImport } from './routes/vhod'
import { Route as PokanaCodeRouteImport } from './routes/pokana.$code'
import { Route as RCodeRouteImport } from './routes/r.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructionsRoute = InstructionsRouteImport.update({
  id: '/instructions',
  path: '/instructions',
  getParentRoute: () => rootRouteImport,
} as any)
const IzvanBulgariaRoute = IzvanBulgariaRouteImport.update({
  id: '/izvan-bulgaria',
  path: '/izvan-bulgaria',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyNoticeRoute = PrivacyNoticeRouteImport.update({
  id: '/privacy-notice',
  path: '/privacy-notice',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const VhodRoute = VhodRouteImport.update({
  id: '/vhod',
  path: '/vhod',
  getParentRoute: () => rootRouteImport,
} as any)
const PokanaCodeRoute = PokanaCodeRouteImport.update({
  id: '/pokana/$code',
  path: '/pokana/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const RCodeRoute = RCodeRouteImport.update({
  id: '/r/$code',
  path: '/r/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/instructions': typeof InstructionsRoute
  '/izvan-bulgaria': typeof IzvanBulgariaRoute
  '/news': typeof NewsRoute
  '/privacy-notice': typeof PrivacyNoticeRoute
  '/profil': typeof ProfilRoute
  '/signup': typeof SignupRoute
  '/vhod': typeof VhodRoute
  '/pokana/$code': typeof PokanaCodeRoute
  '/r/$code': typeof RCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/instructions': typeof InstructionsRoute
  '/izvan-bulgaria': typeof IzvanBulgariaRoute
  '/news': typeof NewsRoute
  '/privacy-notice': typeof PrivacyNoticeRoute
  '/profil': typeof ProfilRoute
  '/signup': typeof SignupRoute
  '/vhod': typeof VhodRoute
  '/pokana/$code': typeof PokanaCodeRoute
  '/r/$code': typeof RCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/instructions': typeof InstructionsRoute
  '/izvan-bulgaria': typeof IzvanBulgariaRoute
  '/news': typeof NewsRoute
  '/privacy-notice': typeof PrivacyNoticeRoute
  '/profil': typeof ProfilRoute
  '/signup': typeof SignupRoute
  '/vhod': typeof VhodRoute
  '/pokana/$code': typeof PokanaCodeRoute
  '/r/$code': typeof RCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/instructions'
    | '/izvan-bulgaria'
    | '/news'
    | '/privacy-notice'
    | '/profil'
    | '/signup'
    | '/vhod'
    | '/pokana/$code'
    | '/r/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/instructions'
    | '/izvan-bulgaria'
    | '/news'
    | '/privacy-notice'
    | '/profil'
    | '/signup'
    | '/vhod'
    | '/pokana/$code'
    | '/r/$code'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/instructions'
    | '/izvan-bulgaria'
    | '/news'
    | '/privacy-notice'
    | '/profil'
    | '/signup'
    | '/vhod'
    | '/pokana/$code'
    | '/r/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  InstructionsRoute: typeof InstructionsRoute
  IzvanBulgariaRoute: typeof IzvanBulgariaRoute
  NewsRoute: typeof NewsRoute
  PrivacyNoticeRoute: typeof PrivacyNoticeRoute
  ProfilRoute: typeof ProfilRoute
  SignupRoute: typeof SignupRoute
  VhodRoute: typeof VhodRoute
  PokanaCodeRoute: typeof PokanaCodeRoute
  RCodeRoute: typeof RCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructions': {
      id: '/instructions'
      path: '/instructions'
      fullPath: '/instructions'
      preLoaderRoute: typeof InstructionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/izvan-bulgaria': {
      id: '/izvan-bulgaria'
      path: '/izvan-bulgaria'
      fullPath: '/izvan-bulgaria'
      preLoaderRoute: typeof IzvanBulgariaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-notice': {
      id: '/privacy-notice'
      path: '/privacy-notice'
      fullPath: '/privacy-notice'
      preLoaderRoute: typeof PrivacyNoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vhod': {
      id: '/vhod'
      path: '/vhod'
      fullPath: '/vhod'
      preLoaderRoute: typeof VhodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pokana/$code': {
      id: '/pokana/$code'
      path: '/pokana/$code'
      fullPath: '/pokana/$code'
      preLoaderRoute: typeof PokanaCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$code': {
      id: '/r/$code'
      path: '/r/$code'
      fullPath: '/r/$code'
      preLoaderRoute: typeof RCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  InstructionsRoute: InstructionsRoute,
  IzvanBulgariaRoute: IzvanBulgariaRoute,
  NewsRoute: NewsRoute,
  PrivacyNoticeRoute: PrivacyNoticeRoute,
  ProfilRoute: ProfilRoute,
  SignupRoute: SignupRoute,
  VhodRoute: VhodRoute,
  PokanaCodeRoute: PokanaCodeRoute,
  RCodeRoute: RCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
